### ISSUE TITLE
Dew point tables are created multiple times

### ISSUE THREAD

**Issue by sdmiked** [sailorsenergy/windb2#21]
For some reason, the `dpt_*` `insert-windb2-file.py` tries to create the `dpt_...` table multiple times:
```
Opening connection using dns: dbname=wrf_nca_v0_2 host=windb2.stage.saildrone.com user=postgres port=5432
Encoding for this connection is UTF8
Time zone being used for this session: UTC
Finished calculating the x,y pair geomkeys.
Processing time for WIND: 2018-08-27T01:00:00.000Z
Inserted 18963, 2.0 height x,y wind points at 18963.0 I/s
Inserted 18963, 10.0 height x,y wind points at 9481.5 I/s
Traceback (most recent call last):
  File "/home/sdfcst01/local/windb2-3.2.1/bin/insert-windb2-file.py", line 87, in <module>
    mask=args.mask, zero_seconds=args.zero_seconds, file_type=file_type)
  File "/home/sdfcst01/local/windb2-3.2.1/bin/../windb2/model/wrf/insert.py", line 114, in insert_variable
    self.create_new_table(domain_key, var_name, ('value',), ('real',))
  File "/home/sdfcst01/local/windb2-3.2.1/bin/../windb2/insert.py", line 256, in create_new_table
    self.windb2.curs.execute("CREATE TABLE " + tableName + "_" + str(domainKey) + " (CHECK (domainkey=" + str(domainKey) + ")) INHERITS (GeoVariable)")
psycopg2.ProgrammingError: relation "dpt_2" already exists
```

**Comment by sdmiked** [comment]
I am unable to reproduce this bug. I believe it was fixed when solving another issue.
